version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    image: php:8.3-fpm-alpine
    user: $DOCKER_USER
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:8.3
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  composer:
    image: composer:2
    user: $DOCKER_USER
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
